modLoader="javafml"
loaderVersion="[40,)"
license="${license}"
issueTrackerURL="https://github.com/tweaked-programs/cccbridge/issues/"

[[mods]]
modId="${archives_base_name}"
version="${version}"
displayName="CC:C Bridge"
updateJSONURL="https://api.modrinth.com/updates/${archives_base_name}/forge_updates.json"
displayURL="https://tweaked-programs.cc/"
logoFile= "iconHD.png"
credits='''I'd like to thank agnor99 for being such a nice person.
Additionally, these people have been contributing:
 Luke A. Hanssen, Rikaisan, Aspenhart, pernydev, TheZoidMaster
'''
authors="Sammy L. Koch"
description='''This mod adds compatibility between the ComputerCraft and Create mod!

Copyright ${copyright_year} Sammy L. Koch'''

[[dependencies.${archives_base_name}]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE" # NONE; BEFORE; AFTER
    side="BOTH"
[[dependencies.${archives_base_name}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${archives_base_name}]]
    modId="create"
    mandatory=true
    versionRange="[${create_version_production},${create_version_production_next})"
    ordering="NONE"
    side="BOTH"
[[dependencies.${archives_base_name}]]
    modId="computercraft"
    mandatory=true
    versionRange="[${cc_version},)"
    ordering="NONE"
    side="BOTH"
